export const peopleData = [
  {
    name: 'ava thomas',
    image: '/faces/face 25.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '11-50',
    'year founded': 2004,
  },
  {
    name: 'owen bell',
    image: '/faces/face 59.png',
    hq: 'California',
    role: 'QA Tester',
    location: 'On-site',
    skill: ['Python', 'SQL'],
    industry: 'Energy',
    headcount: '0-10',
    'year founded': 1991,
  },
  {
    name: 'lucas wright',
    image: '/faces/face 38.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'On-site',
    skill: ['Machine Learning', 'AWS'],
    industry: 'Manufacturing',
    headcount: '11-50',
    'year founded': 2003,
  },
  {
    name: 'hazel bell',
    image: '/faces/face 54.png',
    hq: 'Ohio',
    role: 'DevOps Engineer',
    location: 'On-site',
    skill: ['Docker', 'Kubernetes'],
    industry: 'Transportation',
    headcount: '51-200',
    'year founded': 1996,
  },
  {
    name: 'ava bell',
    image: '/faces/face 7.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2016,
  },
  {
    name: 'noah reed',
    image: '/faces/face 6.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2017,
  },
  {
    name: 'caleb stewart',
    image: '/faces/face 61.png',
    hq: 'Michigan',
    role: 'UX Designer',
    location: 'On-site',
    skill: ['React', 'Scrum'],
    industry: 'Retail',
    headcount: '0-10',
    'year founded': 1989,
  },
  {
    name: 'amelia allen',
    image: '/faces/face 37.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'On-site',
    skill: ['Docker', 'Kubernetes'],
    industry: 'Healthcare',
    headcount: '0-10',
    'year founded': 2001,
  },
  {
    name: 'ava wilson',
    image: '/faces/face 45.png',
    hq: 'New York',
    role: 'UX Designer',
    location: 'Remote',
    skill: ['React', 'AWS'],
    industry: 'Retail',
    headcount: '11-50',
    'year founded': 2011,
  },
  {
    name: 'mia davis',
    image: '/faces/face 5.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2022,
  },
  {
    name: 'zoe hamilton',
    image: '/faces/face 3.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2020,
  },
  {
    name: 'jacob hill',
    image: '/faces/face 34.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'On-site',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2018,
  },
  {
    name: 'charlotte king',
    image: '/faces/face 29.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'Healthcare',
    headcount: '0-10',
    'year founded': 2000,
  },
  {
    name: 'benjamin cooper',
    image: '/faces/face 22.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '11-50',
    'year founded': 2003,
  },
  {
    name: 'mason long',
    image: '/faces/face 12.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2019,
  },
  {
    name: 'harper mitchell',
    image: '/faces/face 21.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '51-200',
    'year founded': 2007,
  },
  {
    name: 'lucas price',
    image: '/faces/face 18.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2012,
  },
  {
    name: 'lucas baker',
    image: '/faces/face 32.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['Docker', 'Kubernetes'],
    industry: 'Healthcare',
    headcount: '0-10',
    'year founded': 2007,
  },
  {
    name: 'jacob price',
    image: '/faces/face 14.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2022,
  },
  {
    name: 'mason clark',
    image: '/faces/face 26.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '0-10',
    'year founded': 2006,
  },
  {
    name: 'sophia hunter',
    image: '/faces/face 13.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2018,
  },
  {
    name: 'logan hall',
    image: '/faces/face 36.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'On-site',
    skill: ['React', 'Node.js'],
    industry: 'Finance',
    headcount: '11-50',
    'year founded': 2006,
  },
  {
    name: 'jackson price',
    image: '/faces/face 8.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2023,
  },
  {
    name: 'emma ward',
    image: '/faces/face 11.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2016,
  },
  {
    name: 'leo ward',
    image: '/faces/face 55.png',
    hq: 'Pennsylvania',
    role: 'Data Scientist',
    location: 'On-site',
    skill: ['Machine Learning', 'Python'],
    industry: 'Healthcare',
    headcount: '11-50',
    'year founded': 1995,
  },
  {
    name: 'amelia adams',
    image: '/faces/face 31.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['React', 'Node.js'],
    industry: 'Finance',
    headcount: '51-200',
    'year founded': 2005,
  },
  {
    name: 'logan lewis',
    image: '/faces/face 48.png',
    hq: 'New York',
    role: 'Data Scientist',
    location: 'On-site',
    skill: ['Python', 'SQL'],
    industry: 'Healthcare',
    headcount: '201-500',
    'year founded': 2009,
  },
  {
    name: 'oliver harris',
    image: '/faces/face 24.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '51-200',
    'year founded': 2008,
  },
  {
    name: 'nora evans',
    image: '/faces/face 58.png',
    hq: 'Florida',
    role: 'Developer',
    location: 'On-site',
    skill: ['JavaScript', 'Node.js'],
    industry: 'Transportation',
    headcount: '11-50',
    'year founded': 1992,
  },
  {
    name: 'jackson scott',
    image: '/faces/face 30.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['Python', 'SQL'],
    industry: 'Retail',
    headcount: '11-50',
    'year founded': 2003,
  },
  {
    name: 'ivy cooper',
    image: '/faces/face 60.png',
    hq: 'Georgia',
    role: 'Business Analyst',
    location: 'On-site',
    skill: ['Agile', 'Git'],
    industry: 'Manufacturing',
    headcount: '11-50',
    'year founded': 1990,
  },
  {
    name: 'oliver cooper',
    image: '/faces/face 10.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2025,
  },
  {
    name: 'ella nelson',
    image: '/faces/face 33.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['Machine Learning', 'AWS'],
    industry: 'Manufacturing',
    headcount: '11-50',
    'year founded': 2010,
  },
  {
    name: 'ethan cole',
    image: '/faces/face 2.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2019,
  },
  {
    name: 'logan ross',
    image: '/faces/face 16.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2015,
  },
  {
    name: 'liam foster',
    image: '/faces/face 4.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2021,
  },
  {
    name: 'amy allen',
    image: '/faces/face 37.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'On-site',
    skill: ['Docker', 'Kubernetes'],
    industry: 'Healthcare',
    headcount: '0-10',
    'year founded': 2001,
  },
  {
    name: 'harper white',
    image: '/faces/face 41.png',
    hq: 'New York',
    role: 'Developer',
    location: 'Remote',
    skill: ['React', 'Node.js'],
    industry: 'Media',
    headcount: '11-50',
    'year founded': 2012,
  },
  {
    name: 'clara stewart',
    image: '/faces/face 56.png',
    hq: 'North Carolina',
    role: 'Technical Writer',
    location: 'On-site',
    skill: ['Scrum'],
    industry: 'Education',
    headcount: '0-10',
    'year founded': 1994,
  },
  {
    name: 'ella price',
    image: '/faces/face 62.png',
    hq: 'Ohio',
    role: 'DevOps Engineer',
    location: 'On-site',
    skill: ['Kubernetes', 'Docker'],
    industry: 'Healthcare',
    headcount: '51-200',
    'year founded': 1988,
  },
  {
    name: 'charlotte robinson',
    image: '/faces/face 49.png',
    hq: 'New York',
    role: 'Technical Writer',
    location: 'Remote',
    skill: ['React', 'Git'],
    industry: 'Media',
    headcount: '11-50',
    'year founded': 2010,
  },
  {
    name: 'isabella ross',
    image: '/faces/face 9.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2024,
  },
  {
    name: 'charlotte miller',
    image: '/faces/face 15.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2017,
  },
  {
    name: 'sophie hunter',
    image: '/faces/face 13.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2018,
  },
  {
    name: 'nathaniel cruz',
    image: '/faces/face 51.png',
    hq: 'California',
    role: 'Security Engineer',
    location: 'On-site',
    skill: ['AWS', 'Git'],
    industry: 'Energy',
    headcount: '11-50',
    'year founded': 1999,
  },
  {
    name: 'ella thompson',
    image: '/faces/face 43.png',
    hq: 'New York',
    role: 'Business Analyst',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'Education',
    headcount: '51-200',
    'year founded': 2014,
  },
  {
    name: 'amelia reid',
    image: '/faces/face 17.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2010,
  },
  {
    name: 'ella bell',
    image: '/faces/face 23.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '0-10',
    'year founded': 2001,
  },
  {
    name: 'amelia grant',
    image: '/faces/face 1.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2018,
  },
  {
    name: 'clara davis',
    image: '/faces/face 64.png',
    hq: 'North Carolina',
    role: 'Technical Writer',
    location: 'On-site',
    skill: ['Scrum', 'Agile'],
    industry: 'Media',
    headcount: '0-10',
    'year founded': 1986,
  },
  {
    name: 'sebastian price',
    image: '/faces/face 53.png',
    hq: 'Michigan',
    role: 'UX Designer',
    location: 'On-site',
    skill: ['React'],
    industry: 'Manufacturing',
    headcount: '11-50',
    'year founded': 1997,
  },
  {
    name: 'leo ross',
    image: '/faces/face 63.png',
    hq: 'Pennsylvania',
    role: 'Data Scientist',
    location: 'On-site',
    skill: ['Python', 'Machine Learning'],
    industry: 'Education',
    headcount: '11-50',
    'year founded': 1987,
  },
  {
    name: 'benjamin anderson',
    image: '/faces/face 42.png',
    hq: 'New York',
    role: 'QA Tester',
    location: 'On-site',
    skill: ['Docker', 'Kubernetes'],
    industry: 'Transportation',
    headcount: '0-10',
    'year founded': 2008,
  },
  {
    name: 'sophia walker',
    image: '/faces/face 27.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'Retail',
    headcount: '11-50',
    'year founded': 2009,
  },
  {
    name: 'logan young',
    image: '/faces/face 28.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'Finance',
    headcount: '51-200',
    'year founded': 2002,
  },
  {
    name: 'jackson walker',
    image: '/faces/face 50.png',
    hq: 'New York',
    role: 'Developer',
    location: 'On-site',
    skill: ['AWS', 'Docker'],
    industry: 'Transportation',
    headcount: '0-10',
    'year founded': 2004,
  },
  {
    name: 'oliver evans',
    image: '/faces/face 44.png',
    hq: 'New York',
    role: 'DevOps Engineer',
    location: 'On-site',
    skill: ['Python', 'SQL'],
    industry: 'Energy',
    headcount: '201-500',
    'year founded': 2000,
  },
  {
    name: 'sophia clark',
    image: '/faces/face 47.png',
    hq: 'New York',
    role: 'Security Engineer',
    location: 'Remote',
    skill: ['Kubernetes', 'Machine Learning'],
    industry: 'Finance',
    headcount: '51-200',
    'year founded': 2013,
  },
  {
    name: 'julian harris',
    image: '/faces/face 57.png',
    hq: 'Texas',
    role: 'System Administrator',
    location: 'On-site',
    skill: ['AWS', 'Docker'],
    industry: 'Media',
    headcount: '51-200',
    'year founded': 1993,
  },
  {
    name: 'mason davis',
    image: '/faces/face 46.png',
    hq: 'New York',
    role: 'System Administrator',
    location: 'On-site',
    skill: ['Docker', 'Git'],
    industry: 'Manufacturing',
    headcount: '0-10',
    'year founded': 2007,
  },
  {
    name: 'mia russell',
    image: '/faces/face 19.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2014,
  },
  {
    name: 'ethan thomas',
    image: '/faces/face 40.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'On-site',
    skill: ['Python', 'SQL'],
    industry: 'Retail',
    headcount: '51-200',
    'year founded': 2015,
  },
  {
    name: 'mia martin',
    image: '/faces/face 39.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'On-site',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2021,
  },
  {
    name: 'ethan coleman',
    image: '/faces/face 20.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'Remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'SaaS',
    headcount: '201-500',
    'year founded': 2005,
  },
  {
    name: 'luna ross',
    image: '/faces/face 52.png',
    hq: 'Georgia',
    role: 'Business Analyst',
    location: 'On-site',
    skill: ['SQL', 'Agile'],
    industry: 'Retail',
    headcount: '0-10',
    'year founded': 1998,
  },
  {
    name: 'charlotte green',
    image: '/faces/face 35.png',
    hq: 'New York',
    role: 'Product Manager',
    location: 'On-site',
    skill: ['Python', 'SQL'],
    industry: 'Retail',
    headcount: '51-200',
    'year founded': 2004,
  },
];
