export const peopleData = [
  {
    name: 'jayden tanaka',
    image: '/faces/face 7.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'Node.js', 'SQL'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2021,
      to: 2025,
    },
  },
  {
    name: 'emma johnson',
    image: '/faces/face 25.png',
    hq: 'Georgia',
    role: 'technical writer',
    location: 'remote',
    skill: ['Python'],
    industry: 'automobile',
    headcount: '11-50',
    'year founded': {
      from: 2021,
      to: 2022,
    },
  },
  {
    name: 'tolu obi',
    image: '/faces/face 4.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2023,
      to: 2024,
    },
  },
  {
    name: 'noah clark',
    image: '/faces/face 50.png',
    hq: 'Texas',
    role: 'data analyst',
    location: 'remote',
    skill: ['PM Tools', 'Figma', 'Docker'],
    industry: 'automobile',
    headcount: '0-10',
    'year founded': {
      from: 2019,
      to: 2019,
    },
  },
  {
    name: 'amara owens',
    image: '/faces/face 53.png',
    hq: 'Pennsylvania',
    role: 'ux designer',
    location: 'on-site',
    skill: ['Docker', 'AWS'],
    industry: 'saas',
    headcount: '51-200',
    'year founded': {
      from: 2022,
      to: 2025,
    },
  },
  {
    name: 'lucas clark',
    image: '/faces/face 5.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2016,
      to: 2022,
    },
  },
  {
    name: 'kwame rodriguez',
    image: '/faces/face 54.png',
    hq: 'Arizona',
    role: 'data analyst',
    location: 'remote',
    skill: ['PM Tools', 'Node.js', 'AWS'],
    industry: 'retail',
    headcount: '201-500',
    'year founded': {
      from: 2011,
      to: 2014,
    },
  },
  {
    name: 'amara gomez',
    image: '/faces/face 32.png',
    hq: 'Illinois',
    role: 'software engineer',
    location: 'remote',
    skill: ['SQL'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2011,
      to: 2019,
    },
  },
  {
    name: 'aisha smith',
    image: '/faces/face 18.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2019,
      to: 2024,
    },
  },
  {
    name: 'aisha scott',
    image: '/faces/face 20.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2018,
      to: 2020,
    },
  },
  {
    name: 'leo rivera',
    image: '/faces/face 33.png',
    hq: 'Florida',
    role: 'qa tester',
    location: 'remote',
    skill: ['React', 'Node.js', 'Docker'],
    industry: 'manufacturing',
    headcount: '201-500',
    'year founded': {
      from: 2010,
      to: 2017,
    },
  },
  {
    name: 'yemi mohammed',
    image: '/faces/face 38.png',
    hq: 'Texas',
    role: 'data analyst',
    location: 'on-site',
    skill: ['Jira', 'AWS'],
    industry: 'manufacturing',
    headcount: '11-50',
    'year founded': {
      from: 2020,
      to: 2025,
    },
  },
  {
    name: 'james anderson',
    image: '/faces/face 30.png',
    hq: 'Arizona',
    role: 'marketing lead',
    location: 'on-site',
    skill: ['React', 'SQL', 'AWS'],
    industry: 'automobile',
    headcount: '51-200',
    'year founded': {
      from: 2014,
      to: 2025,
    },
  },
  {
    name: 'fatima chen',
    image: '/faces/face 60.png',
    hq: 'Arizona',
    role: 'software engineer',
    location: 'remote',
    skill: ['Python', 'Node.js', 'SQL'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2014,
      to: 2024,
    },
  },
  {
    name: 'jonah tanaka',
    image: '/faces/face 8.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'Node.js'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2024,
      to: 2025,
    },
  },
  {
    name: 'leo rodriguez',
    image: '/faces/face 16.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'AWS'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2019,
      to: 2021,
    },
  },
  {
    name: 'jayden mohammed',
    image: '/faces/face 21.png',
    hq: 'Florida',
    role: 'data analyst',
    location: 'remote',
    skill: ['Node.js'],
    industry: 'retail',
    headcount: '51-200',
    'year founded': {
      from: 2022,
      to: 2022,
    },
  },
  {
    name: 'tariq martins',
    image: '/faces/face 49.png',
    hq: 'North Carolina',
    role: 'qa tester',
    location: 'on-site',
    skill: ['Python', 'Jira', 'Node.js', 'SQL'],
    industry: 'saas',
    headcount: '501-2000',
    'year founded': {
      from: 2015,
      to: 2020,
    },
  },
  {
    name: 'rania singh',
    image: '/faces/face 26.png',
    hq: 'Washington',
    role: 'qa tester',
    location: 'on-site',
    skill: ['PM Tools', 'SQL'],
    industry: 'retail',
    headcount: '51-200',
    'year founded': {
      from: 2022,
      to: 2023,
    },
  },
  {
    name: 'grace owens',
    image: '/faces/face 36.png',
    hq: 'Washington',
    role: 'devops engineer',
    location: 'on-site',
    skill: ['PM Tools', 'Python', 'Figma', 'Docker'],
    industry: 'manufacturing',
    headcount: '0-10',
    'year founded': {
      from: 2016,
      to: 2020,
    },
  },
  {
    name: 'jayden ibrahim',
    image: '/faces/face 24.png',
    hq: 'Texas',
    role: 'ux designer',
    location: 'remote',
    skill: ['Jira', 'Figma', 'SQL'],
    industry: 'manufacturing',
    headcount: '11-50',
    'year founded': {
      from: 2013,
      to: 2015,
    },
  },
  {
    name: 'emma garcia',
    image: '/faces/face 1.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'Node.js'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2024,
      to: 2025,
    },
  },
  {
    name: 'zain williams',
    image: '/faces/face 62.png',
    hq: 'Florida',
    role: 'devops engineer',
    location: 'on-site',
    skill: ['Node.js'],
    industry: 'saas',
    headcount: '51-200',
    'year founded': {
      from: 2024,
      to: 2025,
    },
  },
  {
    name: 'chidi thuram',
    image: '/faces/face 45.png',
    hq: 'North Carolina',
    role: 'data analyst',
    location: 'on-site',
    skill: ['PM Tools', 'Python', 'Node.js', 'SQL'],
    industry: 'automobile',
    headcount: '51-200',
    'year founded': {
      from: 2016,
      to: 2018,
    },
  },
  {
    name: 'tariq nguyen',
    image: '/faces/face 59.png',
    hq: 'Pennsylvania',
    role: 'devops engineer',
    location: 'on-site',
    skill: ['Jira', 'AWS'],
    industry: 'manufacturing',
    headcount: '501-2000',
    'year founded': {
      from: 2015,
      to: 2024,
    },
  },
  {
    name: 'emma ali',
    image: '/faces/face 56.png',
    hq: 'Ohio',
    role: 'ux designer',
    location: 'on-site',
    skill: ['Jira', 'Node.js', 'Docker', 'React'],
    industry: 'retail',
    headcount: '11-50',
    'year founded': {
      from: 2024,
      to: 2025,
    },
  },
  {
    name: 'maya kim',
    image: '/faces/face 19.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'SQL'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2018,
      to: 2023,
    },
  },
  {
    name: 'zain scott',
    image: '/faces/face 43.png',
    hq: 'Illinois',
    role: 'ux designer',
    location: 'on-site',
    skill: ['PM Tools', 'Python', 'Figma', 'SQL'],
    industry: 'automobile',
    headcount: '51-200',
    'year founded': {
      from: 2019,
      to: 2024,
    },
  },
  {
    name: 'tolu mohammed',
    image: '/faces/face 22.png',
    hq: 'Florida',
    role: 'marketing lead',
    location: 'on-site',
    skill: ['PM Tools', 'Python', 'React'],
    industry: 'automobile',
    headcount: '501-2000',
    'year founded': {
      from: 2022,
      to: 2022,
    },
  },
  {
    name: 'maya thuram',
    image: '/faces/face 64.png',
    hq: 'California',
    role: 'devops engineer',
    location: 'on-site',
    skill: ['Figma', 'SQL'],
    industry: 'automobile',
    headcount: '51-200',
    'year founded': {
      from: 2010,
      to: 2015,
    },
  },
  {
    name: 'zain lee',
    image: '/faces/face 17.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'Figma'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2022,
      to: 2025,
    },
  },
  {
    name: 'tara ali',
    image: '/faces/face 61.png',
    hq: 'North Carolina',
    role: 'devops engineer',
    location: 'on-site',
    skill: ['PM Tools', 'Python', 'Node.js'],
    industry: 'saas',
    headcount: '0-10',
    'year founded': {
      from: 2016,
      to: 2018,
    },
  },
  {
    name: 'amara tanaka',
    image: '/faces/face 40.png',
    hq: 'Georgia',
    role: 'ux designer',
    location: 'remote',
    skill: ['PM Tools', 'Python', 'Jira'],
    industry: 'manufacturing',
    headcount: '201-500',
    'year founded': {
      from: 2018,
      to: 2021,
    },
  },
  {
    name: 'jonah rivera',
    image: '/faces/face 58.png',
    hq: 'California',
    role: 'technical writer',
    location: 'remote',
    skill: ['Jira', 'Node.js', 'SQL'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2024,
      to: 2025,
    },
  },
  {
    name: 'anika smith',
    image: '/faces/face 2.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2019,
      to: 2022,
    },
  },
  {
    name: 'noah bakari',
    image: '/faces/face 12.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2023,
      to: 2023,
    },
  },
  {
    name: 'jayden singh',
    image: '/faces/face 6.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'Docker'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2018,
      to: 2018,
    },
  },
  {
    name: 'liam ali',
    image: '/faces/face 27.png',
    hq: 'Ohio',
    role: 'ux designer',
    location: 'on-site',
    skill: ['Jira'],
    industry: 'manufacturing',
    headcount: '501-2000',
    'year founded': {
      from: 2013,
      to: 2025,
    },
  },
  {
    name: 'tariq clark',
    image: '/faces/face 14.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'SQL'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2017,
      to: 2022,
    },
  },
  {
    name: 'amara ade',
    image: '/faces/face 35.png',
    hq: 'Florida',
    role: 'qa tester',
    location: 'on-site',
    skill: ['PM Tools', 'Python', 'SQL'],
    industry: 'retail',
    headcount: '0-10',
    'year founded': {
      from: 2022,
      to: 2025,
    },
  },
  {
    name: 'emma nguyen',
    image: '/faces/face 10.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'AWS'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2018,
      to: 2021,
    },
  },
  {
    name: 'nia williams',
    image: '/faces/face 41.png',
    hq: 'Illinois',
    role: 'marketing lead',
    location: 'remote',
    skill: ['Python', 'Figma'],
    industry: 'automobile',
    headcount: '0-10',
    'year founded': {
      from: 2017,
      to: 2021,
    },
  },
  {
    name: 'david garcia',
    image: '/faces/face 55.png',
    hq: 'Texas',
    role: 'ux designer',
    location: 'on-site',
    skill: ['React', 'Figma'],
    industry: 'automobile',
    headcount: '11-50',
    'year founded': {
      from: 2011,
      to: 2011,
    },
  },
  {
    name: 'liam clark',
    image: '/faces/face 31.png',
    hq: 'Illinois',
    role: 'devops engineer',
    location: 'remote',
    skill: ['Figma', 'AWS'],
    industry: 'automobile',
    headcount: '0-10',
    'year founded': {
      from: 2024,
      to: 2025,
    },
  },
  {
    name: 'james ibrahim',
    image: '/faces/face 28.png',
    hq: 'California',
    role: 'marketing lead',
    location: 'on-site',
    skill: ['React', 'SQL'],
    industry: 'retail',
    headcount: '11-50',
    'year founded': {
      from: 2011,
      to: 2013,
    },
  },
  {
    name: 'zara kim',
    image: '/faces/face 63.png',
    hq: 'North Carolina',
    role: 'ux designer',
    location: 'on-site',
    skill: ['Python', 'Jira', 'Figma'],
    industry: 'saas',
    headcount: '501-2000',
    'year founded': {
      from: 2012,
      to: 2025,
    },
  },
  {
    name: 'ethan scott',
    image: '/faces/face 3.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2020,
      to: 2025,
    },
  },
  {
    name: 'chidi rodriguez',
    image: '/faces/face 13.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'SQL'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2016,
      to: 2018,
    },
  },
  {
    name: 'james brown',
    image: '/faces/face 51.png',
    hq: 'Pennsylvania',
    role: 'data analyst',
    location: 'remote',
    skill: ['Python', 'Node.js'],
    industry: 'manufacturing',
    headcount: '0-10',
    'year founded': {
      from: 2024,
      to: 2024,
    },
  },
  {
    name: 'sasha okoye',
    image: '/faces/face 42.png',
    hq: 'Pennsylvania',
    role: 'data analyst',
    location: 'on-site',
    skill: ['React', 'Figma', 'SQL'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2018,
      to: 2024,
    },
  },
  {
    name: 'rania obi',
    image: '/faces/face 23.png',
    hq: 'Texas',
    role: 'software engineer',
    location: 'on-site',
    skill: ['PM Tools', 'AWS'],
    industry: 'saas',
    headcount: '501-2000',
    'year founded': {
      from: 2014,
      to: 2023,
    },
  },
  {
    name: 'elijah garcia',
    image: '/faces/face 52.png',
    hq: 'Washington',
    role: 'qa tester',
    location: 'remote',
    skill: ['Python', 'Jira'],
    industry: 'automobile',
    headcount: '0-10',
    'year founded': {
      from: 2022,
      to: 2022,
    },
  },
  {
    name: 'zain bakari',
    image: '/faces/face 34.png',
    hq: 'Ohio',
    role: 'marketing lead',
    location: 'on-site',
    skill: ['PM Tools', 'React', 'Node.js', 'Docker'],
    industry: 'automobile',
    headcount: '201-500',
    'year founded': {
      from: 2024,
      to: 2024,
    },
  },
  {
    name: 'kwame thuram',
    image: '/faces/face 48.png',
    hq: 'Georgia',
    role: 'software engineer',
    location: 'remote',
    skill: ['Figma', 'SQL', 'AWS'],
    industry: 'retail',
    headcount: '0-10',
    'year founded': {
      from: 2012,
      to: 2016,
    },
  },
  {
    name: 'elijah rivera',
    image: '/faces/face 57.png',
    hq: 'California',
    role: 'qa tester',
    location: 'on-site',
    skill: ['React', 'SQL'],
    industry: 'retail',
    headcount: '11-50',
    'year founded': {
      from: 2011,
      to: 2017,
    },
  },
  {
    name: 'malik kim',
    image: '/faces/face 29.png',
    hq: 'California',
    role: 'ux designer',
    location: 'remote',
    skill: ['Node.js', 'AWS'],
    industry: 'manufacturing',
    headcount: '51-200',
    'year founded': {
      from: 2017,
      to: 2019,
    },
  },
  {
    name: 'kwame brown',
    image: '/faces/face 9.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'Figma'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2018,
      to: 2025,
    },
  },
  {
    name: 'malik chen',
    image: '/faces/face 11.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2024,
      to: 2024,
    },
  },
  {
    name: 'james singh',
    image: '/faces/face 15.png',
    hq: 'New York',
    role: 'product manager',
    location: 'remote',
    skill: ['PM Tools', 'Jira', 'Node.js', 'AWS'],
    industry: 'saas',
    headcount: '201-500',
    'year founded': {
      from: 2019,
      to: 2025,
    },
  },
  {
    name: 'malik martins',
    image: '/faces/face 47.png',
    hq: 'Washington',
    role: 'technical writer',
    location: 'on-site',
    skill: ['PM Tools', 'React', 'AWS'],
    industry: 'manufacturing',
    headcount: '0-10',
    'year founded': {
      from: 2016,
      to: 2025,
    },
  },
  {
    name: 'liam obi',
    image: '/faces/face 44.png',
    hq: 'Georgia',
    role: 'devops engineer',
    location: 'remote',
    skill: ['Figma'],
    industry: 'automobile',
    headcount: '11-50',
    'year founded': {
      from: 2024,
      to: 2025,
    },
  },
  {
    name: 'fatima smith',
    image: '/faces/face 46.png',
    hq: 'Ohio',
    role: 'technical writer',
    location: 'remote',
    skill: ['AWS'],
    industry: 'automobile',
    headcount: '201-500',
    'year founded': {
      from: 2015,
      to: 2021,
    },
  },
  {
    name: 'tariq garcia',
    image: '/faces/face 39.png',
    hq: 'Illinois',
    role: 'marketing lead',
    location: 'remote',
    skill: ['SQL', 'AWS'],
    industry: 'saas',
    headcount: '11-50',
    'year founded': {
      from: 2014,
      to: 2019,
    },
  },
  {
    name: 'ada ade',
    image: '/faces/face 37.png',
    hq: 'Arizona',
    role: 'marketing lead',
    location: 'remote',
    skill: ['Figma', 'Node.js', 'Docker'],
    industry: 'manufacturing',
    headcount: '11-50',
    'year founded': {
      from: 2010,
      to: 2023,
    },
  },
];
